name: abm-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - numpy=1.23
  - matplotlib=3.5.2
  - scipy=1.7.3
  - pip
  - pip:
      - mesa==0.9.0

networkx~=2.8.4
mesa~=1.0.0
setuptools~=63.4.1
click~=8.1.3
numpy~=1.23.0
tornado~=6.1
pandas~=1.4.3
tqdm~=4.64.0
scipy~=1.7.3
intervals~=0.9.2
portion~=2.3.0